spring:
  datasource:
    url: ${LOCAL_DB_URL}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${LOCAL_DB_HOST}
    password: ${LOCAL_DB_PASSWORD}

  jpa:

    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true

    database: mysql

    database-platform: org.hibernate.dialect.MySQL8Dialect

  #    show-sql: true

  jackson:
    property-naming-strategy: SNAKE_CASE

  ## file upload max size (파일 업로드 크기 설정)
  #  servlet:
  #    multipart:
  #      max-file-size: 20MB
  #      max-request-size: 20MB

  flyway:
    enabled: true
    baseline-on-migrate: true

logging.level:
  org.hibernate.SQL: debug
  #  org.hibernate.type: trace
  org.springframework.security: debug
