name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [labeled]

jobs:
  test:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'ChatGPT')
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: Korean
          PROMPT: 당신은 능력 있는 10년차 시니어 개발자로서 프로젝트의 코드 리뷰를 담당하고 있습니다. 코드 리뷰는 한국어로 작성하고 단순하거나 큰 이슈가 없다면 굳이 리뷰하지 않아도 됩니다. 추가로 코드 리뷰를 할 때 일일이 설명하지 않고 꼭 필요한 부분만 짚어서 짧게 설명해주셔도 됩니다.
