version: '3'

services:
  mongodb:
    image: mongo
#    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ${MONGO_LOCAL_PATH}:/data/db
    ports:
      - 27017:27017